services:
  - type: web
    name: vaaa-backend
    env: python
    buildCommand: ./backend/build.sh
    startCommand: gunicorn vaaa.wsgi:application --chdir ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vaaa-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://vaaalivestock.netlify.app"

databases:
  - name: vaaa-db
    databaseName: vaaalivestock_db
    user: postgres
    plan: free